title: Shvanas Documentation
description: Brainstorming and living guidelines for the Shvanas dog ecosystem startup
theme: just-the-docs

nav_external_links:
  - title: Shvanas on GitHub
    url: https://github.com/yourusername/shvanas
    hide_icon: false # set to true to hide the external link icon - defaults to false

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
